-- =============================================================
-- 10.26  Tenant-owned sample data lifecycle
-- -------------------------------------------------------------
-- Production onboarding must never infer ownership from a FAKE-/SAMPLE-
-- prefix. A run records intent and each generated root record is registered
-- explicitly so cleanup can prove what it owns before deleting anything.
-- =============================================================

CREATE TABLE IF NOT EXISTS bms_sample_runs (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id         UUID NOT NULL REFERENCES bms_tenants(id) ON DELETE CASCADE,
  archetype         TEXT NOT NULL CHECK (archetype IN (
    'mini_mart', 'fashion', 'home_kitchen', 'beauty_personal_care',
    'food_beverage', 'gadgets_accessories', 'b2b_wholesale',
    'gifts_seasonal', 'pharmacy', 'pet_supply', 'building_materials',
    'restaurant', 'board_game_cafe', 'other'
  )),
  mode              TEXT NOT NULL CHECK (mode IN ('STARTER_CATALOG', 'FULL_DEMO')),
  generator_version INTEGER NOT NULL DEFAULT 1 CHECK (generator_version > 0),
  status            TEXT NOT NULL CHECK (status IN (
    'RUNNING', 'ACTIVE', 'FAILED', 'DELETING', 'DELETED'
  )),
  requested_by      UUID REFERENCES users(id) ON DELETE SET NULL,
  counts            JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_error        TEXT,
  started_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at      TIMESTAMPTZ,
  deleted_at        TIMESTAMPTZ,
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_bms_sample_runs_one_live
  ON bms_sample_runs (tenant_id)
  WHERE status IN ('RUNNING', 'ACTIVE', 'DELETING');

CREATE TABLE IF NOT EXISTS bms_sample_records (
  sample_run_id     UUID NOT NULL REFERENCES bms_sample_runs(id) ON DELETE CASCADE,
  tenant_id         UUID NOT NULL REFERENCES bms_tenants(id) ON DELETE CASCADE,
  entity_type       TEXT NOT NULL CHECK (entity_type IN (
    'PRODUCT', 'CUSTOMER', 'ORDER', 'CONVERSATION', 'COUPON',
    'PURCHASE_ORDER', 'KITCHEN_STATION', 'BOARD_GAME_AREA',
    'BOARD_GAME_TABLE', 'BOARD_GAME_RATE', 'BOARD_GAME_TITLE',
    'BOARD_GAME_COPY', 'PHARMACY_CASE'
  )),
  entity_key        TEXT NOT NULL,
  baseline          JSONB NOT NULL DEFAULT '{}'::jsonb,
  converted_at      TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (sample_run_id, entity_type, entity_key)
);

CREATE INDEX IF NOT EXISTS idx_bms_sample_records_tenant_run
  ON bms_sample_records (tenant_id, sample_run_id);

ALTER TABLE bms_sample_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE bms_sample_runs FORCE ROW LEVEL SECURITY;
ALTER TABLE bms_sample_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE bms_sample_records FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bms_sample_runs_tenant_isolation ON bms_sample_runs;
CREATE POLICY bms_sample_runs_tenant_isolation ON bms_sample_runs
  USING (tenant_id = NULLIF(current_setting('bms.tenant_id', TRUE), '')::UUID)
  WITH CHECK (tenant_id = NULLIF(current_setting('bms.tenant_id', TRUE), '')::UUID);

DROP POLICY IF EXISTS bms_sample_records_tenant_isolation ON bms_sample_records;
CREATE POLICY bms_sample_records_tenant_isolation ON bms_sample_records
  USING (tenant_id = NULLIF(current_setting('bms.tenant_id', TRUE), '')::UUID)
  WITH CHECK (tenant_id = NULLIF(current_setting('bms.tenant_id', TRUE), '')::UUID);

GRANT SELECT, INSERT, UPDATE, DELETE ON bms_sample_runs TO bms_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON bms_sample_records TO bms_app;

COMMENT ON TABLE bms_sample_runs IS
  'Tenant-scoped production onboarding sample runs. Prefixes are display hints only; this row and bms_sample_records are deletion authority.';
COMMENT ON TABLE bms_sample_records IS
  'Exact root records generated by one sample run, including their baseline for safe cleanup/convert decisions.';
