import type { SystemGuide } from "./types";

const both = (th: string, en: string) => ({ th, en }) as const;
const lists = (th: readonly string[], en: readonly string[]) => ({ th, en }) as const;
const aliases = lists;

function menuGuide(input: {
  id: string;
  module: string;
  route: string;
  coversRoutePrefixes?: readonly string[];
  pageId?: string;
  title: readonly [string, string];
  summary: readonly [string, string];
  aliases?: readonly [readonly string[], readonly string[]];
  requiredPermissions?: SystemGuide["requiredPermissions"];
  anyOfPermissions?: SystemGuide["anyOfPermissions"];
  accessRequirement?: SystemGuide["accessRequirement"];
  prerequisites?: readonly [readonly string[], readonly string[]];
  steps: readonly [readonly string[], readonly string[]];
  warnings?: readonly [readonly string[], readonly string[]];
  relatedCapabilityIds?: readonly string[];
}): SystemGuide {
  const pageId = input.pageId ?? (input.route.replace(/^\/admin\/?/, "").split("/")[0] || "admin");
  return {
    id: input.id,
    module: input.module,
    pageId,
    route: input.route,
    coversRoutePrefixes: input.coversRoutePrefixes,
    title: both(input.title[0], input.title[1]),
    summary: both(input.summary[0], input.summary[1]),
    aliases: aliases(input.aliases?.[0] ?? [input.title[0], pageId], input.aliases?.[1] ?? [input.title[1], pageId]),
    requiredPermissions: input.requiredPermissions ?? [],
    anyOfPermissions: input.anyOfPermissions,
    accessRequirement: input.accessRequirement,
    prerequisites: lists(input.prerequisites?.[0] ?? [], input.prerequisites?.[1] ?? []),
    steps: lists(input.steps[0], input.steps[1]),
    warnings: lists(input.warnings?.[0] ?? [], input.warnings?.[1] ?? []),
    relatedCapabilityIds: input.relatedCapabilityIds ?? [],
  };
}

/** Verified bilingual guides for every routable Admin sidebar surface plus POS workflows. */
export const SYSTEM_GUIDES: readonly SystemGuide[] = [
  {
    id: "reports.create-export", module: "reports", pageId: "reports", route: "/admin/reports",
    title: both("สร้างและส่งออกรายงาน", "Create and export a report"),
    summary: both("เลือกรายงาน ช่วงเวลา และรูปแบบ XLSX, CSV หรือ PDF", "Choose a report, date range, and XLSX, CSV, or PDF format."),
    aliases: aliases(["export excel", "ออก pdf", "ดาวน์โหลดรายงาน"], ["export excel", "create pdf", "download report"]),
    requiredPermissions: ["report.view"],
    prerequisites: lists(["กำหนดช่วงเวลาที่ต้องการ"], ["Choose the required date range."]),
    steps: lists(["เปิดหน้ารายงาน", "เลือกประเภทรายงานและช่วงเวลา", "เลือกรูปแบบไฟล์", "สร้างและดาวน์โหลดไฟล์"], ["Open Reports.", "Choose report type and date range.", "Choose a file format.", "Generate and download the file."]),
    warnings: lists(["PDF ใช้หัวข้อภาษาอังกฤษในปัจจุบัน"], ["PDF headings are currently English."]), relatedCapabilityIds: ["reports.export"],
  },
  {
    id: "loyalty.check-program", module: "loyalty", pageId: "loyalty", route: "/admin/loyalty",
    title: both("ตรวจและตั้งค่าโปรแกรมสะสมแต้ม", "Check and configure loyalty"),
    summary: both("ระบบรองรับสะสมแต้ม แต่ต้องตรวจว่าร้านเปิดโปรแกรมแล้วหรือยัง", "The system supports loyalty, but the shop's live program status must be checked."),
    aliases: aliases(["มีสะสมแต้มไหม", "เปิดแต้ม", "ตั้งค่าแต้ม"], ["do we have loyalty", "enable points", "loyalty settings"]),
    requiredPermissions: ["member.view"],
    prerequisites: lists(["ผู้ตั้งค่าต้องมี loyalty.settings"], ["Configuration requires loyalty.settings."]),
    steps: lists(["เปิดหน้าสมาชิกและแต้ม", "ตรวจสถานะโปรแกรม", "ให้ผู้มีสิทธิ์ตั้งค่าอัตรารับและแลกแต้ม"], ["Open Membership and Loyalty.", "Check program status.", "Have an authorized user configure earning and redemption."]),
    warnings: lists(["อย่าใช้คำว่าร้านเปิดใช้จาก capability อย่างเดียว"], ["Do not infer tenant enablement from product capability alone."]), relatedCapabilityIds: ["loyalty.points"],
  },
  {
    id: "coupons.check-availability", module: "coupons", pageId: "coupons", route: "/admin/coupons",
    title: both("ตรวจคูปองที่ใช้ได้", "Check available coupons"),
    summary: both("แยกคูปองที่ร้านเปิดจากคูปองที่ลูกค้ารายหนึ่งมีสิทธิ์ใช้", "Separate active shop coupons from customer-specific eligibility."),
    aliases: aliases(["มีคูปองอะไร", "คูปองใช้ได้", "ส่วนลดลูกค้า"], ["what coupons", "available coupons", "customer discounts"]),
    requiredPermissions: ["coupon.view"],
    prerequisites: lists(["ถ้าตรวจสิทธิ์ลูกค้า ต้องระบุตัวตนลูกค้าและยอดตะกร้าถ้ามี"], ["Customer eligibility needs a resolved customer and cart subtotal when available."]),
    steps: lists(["เปิดหน้าคูปอง", "ตรวจสถานะและช่วงเวลา", "ถ้าตรวจให้ลูกค้า ให้ตรวจโควตา ยอดขั้นต่ำ และประวัติใช้"], ["Open Coupons.", "Check status and time window.", "For a customer, check quota, minimum spend, and redemption history."]),
    warnings: lists(["Active ไม่ได้แปลว่าใช้ได้กับลูกค้าทุกคน"], ["Active does not mean eligible for every customer."]), relatedCapabilityIds: ["coupons.promotions"],
  },
  {
    id: "users.search-staff", module: "users", pageId: "users", route: "/admin/users",
    title: both("ค้นหาผู้ใช้งานในร้าน", "Find a staff user"),
    summary: both("ค้นหาบัญชีพนักงานในร้านปัจจุบันและดูบทบาทตามสิทธิ์", "Search current-tenant staff accounts and view roles according to access."),
    aliases: aliases(["ร้านมีคนชื่อ", "ค้นพนักงาน", "user เป็นใคร"], ["does the shop have", "find staff", "who is this user"]),
    requiredPermissions: ["user.view"],
    prerequisites: lists(["คำว่า ‘คน’ อาจหมายถึงพนักงานหรือลูกค้า ต้องแยกบริบทก่อน"], ["‘Person’ may mean staff or customer; disambiguate first."]),
    steps: lists(["เปิดหน้าผู้ใช้", "ค้นด้วยชื่อหรือ username", "หากพบชื่อซ้ำให้ผู้ถามเลือก"], ["Open Users.", "Search by name or username.", "Ask the user to choose when matches are ambiguous."]),
    warnings: lists(["ห้ามเปิดเผยว่าบัญชีมีอยู่หรือไม่แก่ผู้ไม่มี user.view"], ["Do not disclose account existence without user.view."]), relatedCapabilityIds: ["users.access"],
  },
  {
    id: "pos.shift", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: both("เปิดและปิดกะ POS", "Open and close a POS shift"),
    summary: both("ตรวจเครื่อง สาขา PIN และยอดเงินก่อนเริ่มหรือปิดกะ", "Check device, branch, PIN, and cash totals before opening or closing a shift."),
    aliases: aliases(["เปิดกะ", "ปิดกะ", "ปิดยอด"], ["open shift", "close shift", "cash up"]),
    requiredPermissions: ["pos.shift.open"],
    prerequisites: lists(["เครื่อง POS ผูกสาขาแล้ว", "พนักงานมี PIN"], ["The POS device is assigned to a branch.", "The cashier has a PIN."]),
    steps: lists(["เลือกเครื่องและยืนยันพนักงาน", "กรอกเงินเปิดกะ", "ขายตามปกติ", "ตรวจรายการค้างและปิดยอดก่อนปิดกะ"], ["Select the device and authenticate the cashier.", "Enter opening cash.", "Operate sales.", "Resolve pending items and reconcile before closing."]),
    warnings: lists(["กะที่มี allocation คืนเงินค้างอยู่ปิดไม่ได้"], ["A shift with pending refund allocations cannot close."]), relatedCapabilityIds: ["pos.operations"],
  },
  {
    id: "dashboard.daily-review", module: "dashboard", pageId: "dashboard", route: "/admin/dashboard",
    title: both("ตรวจภาพรวมร้านประจำวัน", "Review the daily store overview"),
    summary: both("ใช้ Dashboard เพื่อดูยอดขาย งานค้าง และสัญญาณที่ต้องจัดการต่อ", "Use Dashboard to review sales, pending work, and operational signals."),
    aliases: aliases(["dashboard ใช้ยังไง", "ดูภาพรวมร้าน", "เช็กงานวันนี้"], ["how to use dashboard", "store overview", "today's work"]), requiredPermissions: ["report.view"],
    prerequisites: lists(["ข้อมูลต้องมาจากรายการจริงของร้าน"], ["Figures must come from the shop's live records."]),
    steps: lists(["เปิด Dashboard", "เลือกช่วงเวลาที่ต้องการ", "ตรวจตัวเลขและรายการค้าง", "เปิดหน้ารายละเอียดจากการ์ดที่เกี่ยวข้อง"], ["Open Dashboard.", "Choose the period.", "Review figures and pending items.", "Open the relevant detail page."]),
    warnings: lists(["อย่าใช้ตัวเลข placeholder เป็นข้อมูลจริง"], ["Never present placeholder figures as live data."]), relatedCapabilityIds: ["dashboard.overview"],
  },
  {
    id: "products.create", module: "products", pageId: "products", route: "/admin/products",
    title: both("เพิ่มและแก้ไขสินค้า", "Create and edit a product"),
    summary: both("กำหนด SKU ชื่อ ราคา ตัวเลือก รูปภาพ และสถานะขาย", "Configure SKU, name, price, variants, images, and selling status."),
    aliases: aliases(["เพิ่มสินค้า", "แก้สินค้า", "ตั้งราคา", "เพิ่ม SKU"], ["add product", "edit product", "set price", "add SKU"]), requiredPermissions: ["product.view"],
    prerequisites: lists(["การบันทึกต้องมี product.edit", "SKU ต้องไม่ซ้ำในร้าน"], ["Saving requires product.edit.", "SKU must be unique in the shop."]),
    steps: lists(["เปิดหน้าสินค้า", "กดเพิ่มหรือเลือกสินค้าเดิม", "กรอกข้อมูลและตัวเลือก", "ตรวจ validation แล้วบันทึก"], ["Open Products.", "Add a product or select an existing one.", "Enter details and variants.", "Resolve validation and save."]),
    warnings: lists(["Business validation ต้องผ่าน service เดียวกับ import"], ["Business validation must use the same service as imports."]), relatedCapabilityIds: ["catalog.products"],
  },
  {
    id: "inventory.transfer", module: "inventory", pageId: "stock-transfers", route: "/admin/stock-transfers",
    title: both("โอนสต็อกระหว่างสาขา", "Transfer stock between branches"),
    summary: both("ส่งออกจากต้นทางก่อน แล้วจึงรับเข้าที่ปลายทาง", "Send from the source first, then receive at the destination."),
    aliases: aliases(["โอนสต็อก", "ย้ายของสาขา", "ของระหว่างทาง"], ["transfer stock", "move branch inventory", "in transit"]), requiredPermissions: ["inventory.transfer"],
    prerequisites: lists(["มีสาขาต้นทางและปลายทาง", "สต็อกที่ส่งต้องไม่ใช่ของจอง"], ["Source and destination branches exist.", "Reserved stock cannot be sent."]),
    steps: lists(["สร้างใบโอน", "ตรวจจำนวนและส่งจากต้นทาง", "ปลายทางตรวจของจริง", "รับเข้าและบันทึกของขาดถ้ามี"], ["Create a transfer.", "Verify and send from the source.", "Inspect at destination.", "Receive and record any shortage."]),
    warnings: lists(["ของระหว่างทางไม่เป็นสต็อกของสาขาใด", "รับขาดต้องลงเป็นสูญหายระหว่างทาง"], ["In-transit goods belong to no branch.", "Short receipt records loss in transit."]), relatedCapabilityIds: ["inventory.branch"],
  },
  {
    id: "inventory.count", module: "inventory", pageId: "stock-counts", route: "/admin/stock-counts",
    title: both("นับและยืนยันสต็อก", "Count and apply inventory"),
    summary: both("กรอกจำนวนที่นับจริงเทียบ snapshot แล้วให้ผู้มีสิทธิ์ยืนยันส่วนต่าง", "Enter counted quantities against the snapshot, then have an authorized user apply the delta."),
    aliases: aliases(["นับสต็อก", "ปรับยอดจากนับ", "ของหาย"], ["stock count", "apply count", "shrinkage"]), requiredPermissions: ["inventory.count"],
    prerequisites: lists(["ผู้เดินนับมี inventory.count", "ผู้ยืนยันมี inventory.count.apply"], ["Counter has inventory.count.", "Approver has inventory.count.apply."]),
    steps: lists(["สร้างหรือเปิดใบนับ", "กรอกจำนวนจริง", "ตรวจส่วนต่างจาก snapshot", "ให้ผู้มีสิทธิ์ apply"], ["Open a count.", "Enter physical quantities.", "Review snapshot deltas.", "Have an authorized user apply it."]),
    warnings: lists(["ใช้ counted − snapshot ไม่ใช่เขียนยอด absolute", "ห้าม apply จนต่ำกว่าสต็อกที่จอง"], ["Apply counted minus snapshot, not an absolute overwrite.", "Cannot apply below reserved stock."]), relatedCapabilityIds: ["inventory.branch"],
  },
  {
    id: "orders.follow-lifecycle", module: "orders", pageId: "orders", route: "/admin/orders",
    title: both("ติดตามสถานะออร์เดอร์", "Follow an order lifecycle"),
    summary: both("ตรวจรายการ ราคา การชำระ แพ็ก และจัดส่งจากออร์เดอร์เดียว", "Review lines, price, payment, packing, and shipping from one order."),
    aliases: aliases(["สถานะออร์เดอร์", "ออร์เดอร์ค้าง", "แพ็กของ"], ["order status", "pending order", "packing"]), requiredPermissions: ["order.view"],
    prerequisites: lists(["เลือกออร์เดอร์ที่ถูกต้อง"], ["Select the correct order."]),
    steps: lists(["ค้นหาออร์เดอร์", "ตรวจสถานะและข้อมูลลูกค้า", "ทำขั้นตอนถัดไปตามสถานะ", "ตรวจ audit เมื่อผลไม่ตรงคาด"], ["Find the order.", "Review status and customer completeness.", "Perform the allowed next step.", "Review audit history when unexpected."]),
    warnings: lists(["ออร์เดอร์ช่องทางแชทต้องมีที่อยู่ก่อนจัดส่ง", "ยกเลิกและคืนสินค้าเป็นคนละ workflow"], ["Chat-channel orders need an address before shipping.", "Cancel and return are separate workflows."]), relatedCapabilityIds: ["orders.lifecycle"],
  },
  {
    id: "payments.review-payment", module: "payments", pageId: "payments", route: "/admin/payment",
    title: both("ตรวจและยืนยันการชำระเงิน", "Review and confirm a payment"),
    summary: both("เปรียบเทียบหลักฐานกับออร์เดอร์ แล้วให้ผู้มีสิทธิ์ตัดสินใจ", "Compare evidence with the order, then have an authorized user decide."),
    aliases: aliases(["ตรวจสลิป", "ยืนยันเงิน", "ปฏิเสธเงิน"], ["review slip", "confirm payment", "reject payment"]), requiredPermissions: ["payment.view"],
    prerequisites: lists(["การยืนยันต้องมี payment.confirm"], ["Confirmation requires payment.confirm."]),
    steps: lists(["เปิดรายการรอตรวจ", "เทียบยอดและข้อมูลที่ตรวจได้", "บันทึกหมายเหตุถ้าจำเป็น", "ยืนยันหรือปฏิเสธด้วยสิทธิ์ที่เหมาะสม"], ["Open a pending payment.", "Compare verified amount and details.", "Add a note if needed.", "Confirm or reject with the proper access."]),
    warnings: lists(["OCR/AI เป็นคำแนะนำเท่านั้น", "ห้าม auto-confirm"], ["OCR/AI is advisory only.", "Never auto-confirm."]), relatedCapabilityIds: ["payments.review"],
  },
  {
    id: "shipping.create", module: "shipping", pageId: "shipping", route: "/admin/shipment",
    title: both("สร้างการจัดส่งและบันทึกเลขพัสดุ", "Create a shipment and tracking number"),
    summary: both("สร้าง shipment หลังข้อมูลจัดส่งครบ แล้วอัปเดต tracking", "Create a shipment after delivery data is complete, then update tracking."),
    aliases: aliases(["สร้างพัสดุ", "ใส่เลขพัสดุ", "Kerry", "Flash"], ["create shipment", "tracking number", "Kerry", "Flash"]), requiredPermissions: ["shipping.view"],
    prerequisites: lists(["การสร้างต้องมี shipping.create", "ออร์เดอร์ที่ต้องส่งมีที่อยู่ครบ"], ["Creation requires shipping.create.", "The order has a complete shipping address."]),
    steps: lists(["เลือกออร์เดอร์", "ตรวจที่อยู่และผู้รับ", "สร้าง shipment", "บันทึก tracking และติดตามสถานะ"], ["Select the order.", "Verify recipient and address.", "Create the shipment.", "Record tracking and follow status."]),
    warnings: lists(["Flash/Kerry ยังไม่ใช่ live adapters", "การจอง carrier ไม่รันใน transaction fulfillment"], ["Flash/Kerry are not live adapters.", "Carrier booking does not run inside the fulfillment transaction."]), relatedCapabilityIds: ["shipping.fulfillment"],
  },
  {
    id: "purchase.receive", module: "purchase", pageId: "purchase", route: "/admin/purchase",
    title: both("รับสินค้าเข้าใบสั่งซื้อ", "Receive a purchase order"),
    summary: both("ตรวจของจริงและรับเข้าเต็มจำนวนหรือบางส่วนตามสิทธิ์", "Inspect physical goods and receive a full or partial quantity."),
    aliases: aliases(["รับ PO", "รับของเข้า", "รับบางส่วน"], ["receive PO", "receive stock", "partial receipt"]), requiredPermissions: ["purchase.view"],
    prerequisites: lists(["ผู้รับต้องมี purchase.receive", "PO อยู่สถานะที่รับได้"], ["Receiver has purchase.receive.", "The PO is in a receivable state."]),
    steps: lists(["เปิด PO", "เทียบของจริงกับรายการ", "กรอกจำนวนรับ", "ยืนยันเพื่อบันทึกสต็อกและ movement พร้อมกัน"], ["Open the PO.", "Compare physical goods with lines.", "Enter received quantities.", "Confirm the atomic stock and movement write."]),
    warnings: lists(["ห้ามเขียน stock แยกจาก receipt transaction"], ["Never write stock outside the receipt transaction."]), relatedCapabilityIds: ["purchase.orders"],
  },
  {
    id: "customers.customer-360", module: "customers", pageId: "customers", route: "/admin/customers",
    title: both("ดูภาพรวมลูกค้า Customer 360", "Use Customer 360"),
    summary: both("ดูตัวตน ออร์เดอร์ คูปอง ที่อยู่ บันทึก และ timeline ของลูกค้าเดียว", "Review identity, orders, coupons, addresses, notes, and timeline for one customer."),
    aliases: aliases(["Customer 360", "ประวัติลูกค้า", "ลูกค้าเคยซื้ออะไร"], ["Customer 360", "customer history", "past purchases"]), requiredPermissions: ["customer.view"],
    prerequisites: lists(["เลือกตัวตนลูกค้าที่ถูกต้อง"], ["Resolve the correct customer identity."]),
    steps: lists(["ค้นหาลูกค้า", "เปิด Customer 360", "เลือกแท็บข้อมูลที่ต้องการ", "ทำ Quick Action เฉพาะที่มีสิทธิ์"], ["Find the customer.", "Open Customer 360.", "Choose the relevant tab.", "Use only authorized quick actions."]),
    warnings: lists(["ข้อมูล customer-facing ต้องลด PII เท่าที่จำเป็น", "ชื่อซ้ำต้องให้ผู้ใช้เลือก"], ["Customer-facing AI data must minimize PII.", "Ambiguous matches require selection."]), relatedCapabilityIds: ["customers.crm"],
  },
  {
    id: "inbox.handle-conversation", module: "inbox", pageId: "inbox", route: "/admin/inbox",
    title: both("จัดการบทสนทนาใน Inbox", "Handle an Inbox conversation"),
    summary: both("อ่านบริบท มอบหมาย ติดแท็ก เพิ่มโน้ต และตอบผ่านช่องทางจริง", "Read context, assign, tag, note, and reply over the real channel."),
    aliases: aliases(["ตอบแชท", "มอบหมายแชท", "ปิดบทสนทนา"], ["reply to chat", "assign conversation", "close conversation"]), requiredPermissions: ["inbox.view"],
    prerequisites: lists(["การตอบต้องมี inbox.reply", "ช่องทางต้องพร้อมส่ง"], ["Replying requires inbox.reply.", "The channel must support outbound messaging."]),
    steps: lists(["เปิดบทสนทนา", "อ่านประวัติแบบ bounded", "มอบหมายหรือเพิ่มโน้ต", "ตรวจข้อความและส่ง"], ["Open the conversation.", "Read bounded history.", "Assign or add a note.", "Review and send the reply."]),
    warnings: lists(["ส่งได้ body และ attachment เดียว", "ห้ามส่งลิงก์ /admin ให้ลูกค้า"], ["Replies support body plus one attachment.", "Never send /admin links to customers."]), relatedCapabilityIds: ["inbox.omnichannel"],
  },
  {
    id: "followup.review-queue", module: "followup", pageId: "followup", route: "/admin/followup-queue",
    title: both("ตรวจคิวติดตามลูกค้า", "Review the follow-up queue"),
    summary: both("ตรวจงานติดตามและ retention proposal ก่อนติดต่อ", "Review follow-up jobs and retention proposals before contact."),
    aliases: aliases(["คิว follow up", "ติดตามลูกค้า", "retention"], ["follow-up queue", "customer follow-up", "retention"]), requiredPermissions: ["followup.view"],
    prerequisites: lists(["การจัดการต้องมี followup.manage หรือ retention.manage ตามแท็บ"], ["Management requires followup.manage or retention.manage for the relevant tab."]),
    steps: lists(["เปิดคิว", "แยก follow-up กับ retention", "ตรวจเหตุผลและหลักฐาน", "รับข้อเสนอหรือดำเนินการตามสิทธิ์"], ["Open the queue.", "Distinguish follow-up from retention.", "Review rationale and evidence.", "Accept or act according to access."]),
    warnings: lists(["Holdout ห้ามติดต่อ", "สินค้าแนะนำต้องมีประวัติตะกร้ายืนยัน"], ["Holdout rows cannot be contacted.", "Product suggestions require verified basket history."]), relatedCapabilityIds: ["followup.retention"],
  },
  {
    id: "pos.manual-discount", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: both("ให้ส่วนลดด้วยมือใน POS", "Apply a manual POS discount"),
    summary: both("ใส่ส่วนลดแล้วให้บุคคลที่สองอนุมัติด้วย PIN", "Enter the discount and obtain a second person's PIN approval."),
    aliases: aliases(["ส่วนลด POS", "ลดราคาด้วยมือ", "PIN คนที่สอง"], ["POS discount", "manual discount", "second PIN"]), requiredPermissions: ["pos.sell"],
    prerequisites: lists(["เปิดกะแล้ว", "มีสินค้าในบิล", "ผู้อนุมัติมี pos.discount.approve"], ["A shift is open.", "The bill has items.", "The approver has pos.discount.approve."]),
    steps: lists(["เลือกส่วนลด", "ระบุจำนวนหรือเปอร์เซ็นต์", "ให้ผู้อนุมัติคนที่สองกรอก PIN", "ตรวจยอดสุทธิก่อนรับเงิน"], ["Choose discount.", "Enter amount or percentage.", "Have a second person enter their PIN.", "Review the net total before payment."]),
    warnings: lists(["ผู้ขายกับผู้อนุมัติต้องเป็นคนละคนแม้ผู้ขายถือสิทธิ์เอง"], ["Operator and approver must be different people even if the operator holds the permission."]), relatedCapabilityIds: ["pos.operations"],
  },
  {
    id: "pos.void-return", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: both("แยก Void ออกจาก Return", "Distinguish Void from Return"),
    summary: both("Void คือย้อนบิลที่กดผิด ส่วน Return คือรับสินค้าคืนหลังการขาย", "Void reverses an erroneous bill; Return accepts goods back after sale."),
    aliases: aliases(["void ต่างจาก return", "ยกเลิกบิล POS", "คืนสินค้า POS"], ["void versus return", "cancel POS bill", "POS return"]), requiredPermissions: ["order.return"],
    prerequisites: lists(["ต้องอ้างบิลและตรวจสิทธิ์ของ action"], ["Reference the sale and check the action permission."]),
    steps: lists(["ค้นบิล", "เลือก Void หรือ Return ให้ตรงเหตุผล", "ตรวจจำนวนและวิธีคืนเงิน", "ให้ผู้อนุมัติที่จำเป็นกรอก PIN"], ["Find the sale.", "Choose Void or Return for the actual reason.", "Review quantities and refund method.", "Obtain required second-person approval."]),
    warnings: lists(["Void stamp เอกสารภาษี และ audit ต้องอยู่ transaction เดียวกับ reversal"], ["Void stamp, tax cancellation, and audit belong in the reversal transaction."]), relatedCapabilityIds: ["pos.operations"],
  },
  {
    id: "pos.cash-movement", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: both("บันทึกเงินเข้าออกลิ้นชัก", "Record drawer cash movement"),
    summary: both("ใช้เมนูเงินเข้า/ออกสำหรับรายการที่ไม่ใช่การขาย", "Use cash in/out for drawer movements unrelated to a sale."),
    aliases: aliases(["เงินเข้าลิ้นชัก", "เงินออกลิ้นชัก", "cash movement", "เปิดลิ้นชัก", "no sale", "แลกแบงก์ย่อย", "เงินสดในลิ้นชัก"], ["cash in", "cash out", "drawer movement", "open drawer", "no sale", "make change", "drawer cash"]), requiredPermissions: ["pos.cash.movement"],
    prerequisites: lists(["มีกะเปิดอยู่", "ระบุเหตุผลและ idempotency key"], ["A shift is open.", "Provide a reason and idempotency key."]),
    steps: lists(["เลือกเงินเข้าหรือเงินออก", "กรอกยอดและเหตุผล", "เงินออกให้คนที่สองอนุมัติ", "ถ้าแค่เปิดลิ้นชักเพื่อแลกแบงก์ ใช้ No-sale พร้อมระบุเหตุผล", "ตรวจรายการในรายงานกะ"], ["Choose cash in or out.", "Enter amount and reason.", "Cash-out needs second-person approval.", "To open the drawer without selling, use No-sale and give a reason.", "Verify it in the shift report."]),
    warnings: lists(["ห้ามบันทึกเงินออกซ้ำเมื่อ response หาย", "เงินออกต้องมีคนที่สอง", "No-sale ไม่ต้องมีผู้อนุมัติแต่ต้องมีเหตุผลทุกครั้ง และขึ้นบนสรุปกะ (สิทธิ์ pos.nosale)"], ["Do not duplicate cash-out after a lost response.", "Cash-out requires a second person.", "No-sale needs no approver but always needs a reason and appears on the shift report (pos.nosale)."]), relatedCapabilityIds: ["pos.operations"],
  },
  menuGuide({
    id: "pos.build-sale", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["ขายสินค้าและจัดตะกร้า POS", "Build a POS sale"], summary: ["เลือกผู้ขาย ยิงหรือค้นสินค้า ตรวจจำนวน ราคา pack และ serial ก่อนรับเงิน", "Identify the cashier, scan or find items, and verify quantity, pack pricing, and serials before payment."],
    aliases: [["เมนูขาย", "ยิงสินค้า", "ตะกร้า POS", "สแกนบาร์โค้ด", "เลขเครื่อง", "serial", "imei", "ราคาส่ง", "โปรโมชั่น", "สินค้าชุด", "ค่าถุง", "ค่าบริการ"], ["sale tab", "scan product", "POS cart", "scan barcode", "serial number", "imei", "tier price", "promotion", "bundle", "bag fee", "service charge"]], requiredPermissions: ["pos.sell"],
    prerequisites: [["เครื่องจับคู่และผูกสาขาแล้ว", "เปิดกะและยืนยัน PIN ผู้ขาย"], ["The register is paired and assigned to a branch.", "A shift is open and the cashier PIN is verified."]],
    steps: [["เลือกผู้ขายและใส่ PIN", "ยิงบาร์โค้ดหรือค้นสินค้า", "ตรวจไซซ์ pack จำนวน ราคาและ stock", "ระบุ serial ถ้าสินค้าบังคับ", "ไปขั้นรับชำระ"], ["Select the cashier and enter the PIN.", "Scan a barcode or search.", "Review size, pack, quantity, price, and stock.", "Enter required serials.", "Continue to payment."]],
    warnings: [["ก่อนรับเงิน backend จะตรวจราคา promotion pack และ stock ใหม่", "บาร์โค้ด scanner ใช้ prefix ที่ตั้งค่า ไม่ใช้ timing/focus เป็นหลักฐาน"], ["The backend rechecks pricing, promotions, packs, and stock before payment.", "Scanner capture requires a configured prefix; timing/focus is not proof."]], relatedCapabilityIds: ["pos.operations"],
  }),
  menuGuide({
    id: "pos.take-payment", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["รับชำระและจ่ายผสม", "Take payment and split tender"], summary: ["เลือกรูปแบบรับเงิน ตรวจยอดรับ/เงินทอน และยืนยันการขายหนึ่งครั้ง", "Choose tender, verify received cash/change, and settle the sale once."],
    aliases: [["รับเงิน", "เงินสด QR บัตร", "จ่ายผสม"], ["take payment", "cash QR card", "split tender"]], requiredPermissions: ["pos.sell"],
    prerequisites: [["มีสินค้าในบิลและเปิดกะแล้ว"], ["The cart has items and the shift is open."]], steps: [["เลือกเงินสด QR บัตร วอลเล็ท หรือจ่ายผสม", "กรอกยอดแต่ละช่องทาง", "ตรวจยอดรับและเงินทอน", "ยืนยันขายและรอผลเดิมก่อนลองซ้ำ"], ["Choose cash, QR, card, wallet, or split tender.", "Enter each tender amount.", "Review received amount and change.", "Confirm once and wait for the original result before retrying."]],
    warnings: [["ช่องทางรับเงินต้องมาจาก config ร้าน", "idempotency key ป้องกันการขายซ้ำเมื่อ response หาย"], ["Payment methods must come from shop configuration.", "The idempotency key prevents duplicate sales after a lost response."]], relatedCapabilityIds: ["pos.operations"],
  }),
  menuGuide({
    id: "pos.member-coupon-points", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["ใช้สมาชิก คูปอง แต้ม และส่วนลด", "Use members, coupons, points, and discounts"], summary: ["ค้นสมาชิกก่อนชำระ ตรวจคูปอง/แต้มจริง และให้คนที่สองอนุมัติส่วนลด manual", "Resolve the member before payment, verify coupons/points, and require a second person for manual discounts."],
    aliases: [["สมาชิก POS", "ใช้แต้ม", "คูปองหน้าร้าน"], ["POS member", "redeem points", "counter coupon"]], requiredPermissions: ["pos.sell"],
    steps: [["ค้นสมาชิกด้วยเบอร์หรือเลขสมาชิก", "ตรวจ tier แต้มและคูปอง", "เลือกสิทธิ์ที่จะใช้", "ตรวจยอดสุทธิ", "ส่วนลด manual ให้คนที่สองใส่ PIN"], ["Find the member by phone or member number.", "Review tier, points, and coupons.", "Choose the benefit.", "Review the net total.", "A manual discount needs a second PIN."]],
    warnings: [["แต้มถูกหักใน transaction ขาย ไม่ใช่ตอนค้น", "Active coupon ไม่ได้แปลว่าลูกค้าคนนี้ใช้ได้"], ["Points are deducted in the sale transaction, not during lookup.", "An active coupon is not automatically eligible for this customer."]], relatedCapabilityIds: ["loyalty.points", "coupons.promotions", "pos.operations"],
  }),
  menuGuide({
    id: "pos.receive-purchase", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["รับสินค้าจาก PO ที่ POS", "Receive a PO at POS"], summary: ["เลือก PO สแกนเป็นร่าง ตรวจจำนวน lot/expiry แล้วรับเข้าสต็อกสาขาของเครื่อง", "Select a PO, scan a draft, review quantity/lot/expiry, and receive into the register branch."],
    aliases: [["เมนูรับของ", "รับ PO", "ของเข้าที่ POS"], ["receive tab", "receive PO", "POS receiving"]], requiredPermissions: ["purchase.receive"],
    prerequisites: [["เครื่องผูกสาขา", "มี PO สถานะที่รับได้"], ["The register has a branch.", "The PO is in a receivable state."]], steps: [["เปิดแท็บรับของ", "เลือก PO", "สแกนหรือกรอกจำนวนพร้อม lot/expiry", "ตรวจ draft", "ยืนยันรับครั้งเดียว"], ["Open Receive.", "Choose a PO.", "Scan or enter quantities with lot/expiry.", "Review the draft.", "Confirm receipt once."]],
    warnings: [["สาขามาจาก device ไม่รับจาก request", "stock movement และ audit commit พร้อมกัน"], ["The branch comes from the device, never the request.", "Stock movement and audit commit together."]], relatedCapabilityIds: ["purchase.orders", "pos.operations"],
  }),
  menuGuide({
    id: "pos.manage-deposit", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["รับและปิดมัดจำ", "Take and settle a deposit"], summary: ["รับมัดจำ รับเพิ่ม รับยอดคงเหลือ และปิดรายการของสาขาเครื่อง", "Take a deposit, add payment, collect the balance, and close the branch deposit."],
    aliases: [["เมนูมัดจำ", "รับยอดคงเหลือ", "ปิดมัดจำ"], ["deposit tab", "collect balance", "settle deposit"]], requiredPermissions: ["pos.deposit.take"],
    steps: [["เปิดแท็บมัดจำ", "ค้นหรือสร้างรายการ", "รับเงินครั้งแรก/รับเพิ่ม", "เมื่อครบให้ใช้รับยอดคงเหลือเพื่อส่งของและตัด stock"], ["Open Deposits.", "Find or create the record.", "Take the first or an additional payment.", "Use balance settlement to deliver and deduct stock."]],
    warnings: [["ยกเลิกต้องมี pos.deposit.cancel", "สินค้าบังคับ serial ต้องยิงสินค้าและ serial จริงก่อนปิดยอด"], ["Cancellation requires pos.deposit.cancel.", "Serial-tracked items need the real item and serial before settlement."]], relatedCapabilityIds: ["pos.deposits"],
  }),
  menuGuide({
    id: "pos.park-resume", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["พักและเรียกบิลกลับ", "Park and resume a bill"], summary: ["พักตะกร้าชั่วคราวในกะและเรียกกลับด้วยราคา/สต็อกปัจจุบัน", "Temporarily park a cart in the shift and resume using current price and stock."],
    aliases: [["พักบิล", "เรียกบิล", "park bill"], ["park bill", "resume cart", "held sale"]], requiredPermissions: ["pos.sell"],
    steps: [["จัดตะกร้า", "กดพักบิลและใส่ชื่ออ้างอิง", "เปิดรายการพัก", "เลือกบิลกลับมาตรวจใหม่ก่อนขาย"], ["Build the cart.", "Park it with a reference.", "Open parked bills.", "Resume and recheck before selling."]],
    warnings: [["พักได้ไม่เกิน 20 บิลต่อกะ", "ไม่จอง stock และไม่ล็อกราคา"], ["A shift can hold up to 20 parked bills.", "Parking reserves no stock and locks no price."]], relatedCapabilityIds: ["pos.operations"],
  }),
  menuGuide({
    id: "pos.receipt-display", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["ใช้ใบเสร็จ เครื่องพิมพ์ และจอลูกค้า", "Use receipts, printers, and customer display"], summary: ["ตรวจ preview พิมพ์/ส่งใบเสร็จ และใช้จอลูกค้าที่ไม่แสดงเครื่องมือพนักงาน", "Preview, print or send receipts, and use a customer display without staff controls."],
    aliases: [["พิมพ์ใบเสร็จ", "จอลูกค้า", "customer display", "ใบกำกับภาษี", "ใบกำกับภาษีอย่างย่อ", "ใบกำกับภาษีเต็มรูป", "ส่งใบเสร็จอีเมล", "ส่งใบเสร็จ LINE", "พิมพ์ใบเสร็จซ้ำ"], ["print receipt", "customer display", "receipt printer", "tax invoice", "abbreviated tax invoice", "full tax invoice", "email receipt", "LINE receipt", "reprint receipt"]], requiredPermissions: ["pos.sell"],
    steps: [["ตั้งเครื่องพิมพ์ใน POS settings", "ขายและเปิดใบเสร็จ", "ตรวจ preview", "พิมพ์หรือส่งตามช่องทางที่รองรับ"], ["Configure the printer in POS settings.", "Complete a sale and open the receipt.", "Review the preview.", "Print or send through a supported channel."]],
    warnings: [["หน้า /pos/display ห้ามแสดง Assistant หรือ control ของพนักงาน"], ["/pos/display must not expose the Assistant or staff controls."]], relatedCapabilityIds: ["pos.operations"],
  }),
  menuGuide({
    id: "pos.device-settings", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["ตั้งค่า Scanner และอุปกรณ์ POS", "Configure POS scanner and device settings"], summary: ["ตั้ง scanner prefix เครื่องพิมพ์และจอลูกค้าให้ตรงกับเครื่องที่จับคู่", "Configure scanner prefix, printer, and customer display for the paired register."],
    aliases: [["ตั้งค่า scanner", "เมนูตั้งค่า POS", "prefix mode"], ["scanner settings", "POS settings tab", "prefix mode"]], requiredPermissions: ["pos.sell"],
    steps: [["เปิดเมนูตั้งค่าที่ POS", "เลือก Prefix Mode และกำหนด prefix ที่ scanner ส่งจริง", "ตั้งเครื่องพิมพ์/จอลูกค้าตามอุปกรณ์", "ทดสอบสแกนโดยโฟกัสอยู่คนละช่อง"], ["Open POS settings.", "Choose Prefix Mode and the real scanner prefix.", "Configure printer/customer display.", "Test scanning while another input is focused."]],
    warnings: [["อย่าใช้ความเร็วการพิมพ์หรือ focus เป็นหลักฐานว่าเป็น scanner", "ค่าเครื่องต้องสอดคล้องกับ POS Devices และสาขา"], ["Do not use typing speed or focus as proof of a scanner.", "Device settings must match POS Devices and its branch."]], relatedCapabilityIds: ["pos.operations"],
  }),
  menuGuide({
    id: "pos.expense-petty-cash", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["บันทึกค่าใช้จ่ายและเงินสดย่อย", "Record expenses and petty cash"], summary: ["แยกค่าใช้จ่าย การเบิกเงินสดย่อย และ cash movement ให้ตรงต้นเหตุ", "Keep expenses, petty-cash advances, and drawer movements distinct."],
    aliases: [["ค่าใช้จ่าย POS", "เงินสดย่อย", "สำรองจ่าย"], ["POS expense", "petty cash", "personal funds"]], anyOfPermissions: ["pos.expense.create", "pos.petty_cash.manage", "pos.cash.movement"],
    steps: [["เลือกประเภทค่าใช้จ่าย/เงินสดย่อย/เงินเข้าออก", "กรอกยอด เหตุผล และหลักฐาน", "ให้คนที่สองอนุมัติเมื่อเป็นเงินออก", "ปิดยอดเบิกก่อนปิดกะ"], ["Choose expense, petty cash, or cash movement.", "Enter amount, reason, and evidence.", "Obtain second-person approval for cash-out.", "Settle advances before closing the shift."]],
    warnings: [["ยอดขายเงินสดเข้า expected drawer อัตโนมัติ ห้ามลง cash-in ซ้ำ"], ["Cash sales enter expected drawer cash automatically; never duplicate them as cash-in."]], relatedCapabilityIds: ["pos.expenses"],
  }),
  menuGuide({
    id: "pos.credit-sale", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["ขายเชื่อและเก็บเงินลูกหนี้ที่เคาน์เตอร์", "Sell on credit and collect receivables"],
    summary: ["เปิดบิลเชื่อให้ลูกค้าที่มีวงเงิน และรับชำระหนี้ใบเก่าจากเครื่องขาย", "Open a credit bill for a customer with a limit, and collect payment against open invoices at the register."],
    aliases: [["ขายเชื่อ", "ลงบัญชีไว้ก่อน", "ลูกหนี้", "เก็บเงินลูกหนี้", "วงเงินลูกค้า"], ["credit sale", "sell on account", "receivable", "collect debt", "credit limit"]],
    requiredPermissions: ["pos.sell"],
    prerequisites: [["ลูกค้าถูกระบุตัวบนบิลและมีบัญชีเครดิตพร้อมวงเงิน", "คนที่ปล่อยเชื่อต้องมี ar.sell — ถ้าคนขายไม่มี ให้คนที่มีกด PIN (เป็นคนเดียวกับคนขายได้)", "การรับชำระต้องมี ar.collect"], ["The customer is identified on the bill and has a credit account with a limit.", "Selling on credit needs ar.sell — if the cashier lacks it, a holder enters their PIN (it may be the same person).", "Collecting payment needs ar.collect."]],
    steps: [["ระบุลูกค้าบนบิลก่อนไปขั้นรับชำระ", "เลือกวิธีชำระเป็นเชื่อ (จ่ายสดบางส่วนแล้วค้างที่เหลือก็ได้)", "ถ้า server บอกว่าคนขายไม่มีสิทธิ์ ให้ผู้มีสิทธิ์กด PIN", "รับชำระใบเก่าจากเมนูลูกหนี้ โดยเลือกบัญชีและวิธีรับเงิน"], ["Identify the customer before the payment step.", "Choose credit as the tender (part cash, part credit is allowed).", "If the server says the cashier lacks access, have a permitted user enter their PIN.", "Collect an open invoice from the receivables menu by choosing the account and tender."]],
    warnings: [["ขายเชื่อไม่ใช่มัดจำ — ของออกจากร้านและบิลปิดครบเส้นแล้ว เหลือแต่หนี้", "ยอดเชื่อไม่ใช่เงินสด จึงไม่เข้ายอดที่ควรมีในลิ้นชัก", "เงินที่เก็บได้ทีหลังเข้าลิ้นชักของกะที่รับเงิน ไม่ใช่กะที่ขาย", "รับเกินยอดค้างถูกปฏิเสธ ไม่ได้เก็บเป็นเงินล่วงหน้า", "วงเงินถูกตรวจอีกครั้งในทรานแซกชันที่ตัดสต็อก จอที่บอกว่าพอ ไม่ได้แปลว่าผ่านแน่"], ["A credit sale is not a deposit: the goods leave and the bill closes; only the debt remains.", "Credit is not cash and never enters expected drawer cash.", "Money collected later belongs to the shift that received it, not the shift that sold.", "Paying more than the outstanding balance is rejected, not kept as prepayment.", "The limit is rechecked inside the stock-deducting transaction; an on-screen pass is not a guarantee."]],
    relatedCapabilityIds: ["receivables.credit-sales", "pos.operations"],
  }),
  menuGuide({
    id: "pos.blind-return", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["คืนสินค้าโดยไม่มีใบเสร็จ", "Return without the original receipt"],
    summary: ["รับคืนของที่หาบิลต้นทางไม่ได้ โดยต้องมีผู้อนุมัติคนที่สองเสมอ", "Accept goods back when the original sale cannot be found, always with a second approver."],
    aliases: [["คืนของไม่มีใบเสร็จ", "ใบเสร็จหาย", "คืนแบบไม่มีบิล", "blind return"], ["no receipt return", "lost receipt", "blind return", "return without bill"]],
    anyOfPermissions: ["order.return", "pos.return.noreceipt"],
    prerequisites: [["เปิดกะแล้วและมีเงินสดในลิ้นชักพอจ่ายคืน", "ผู้อนุมัติต้องมี pos.return.noreceipt (seed ให้ Manager เท่านั้น) และต้องเป็นคนละคนกับคนขาย"], ["A shift is open and the drawer holds enough cash to refund.", "The approver holds pos.return.noreceipt (seeded to Manager only) and must be a different person from the cashier."]],
    steps: [["ลองค้นบิลต้นทางก่อนเสมอ — ถ้าเจอให้ใช้ Return ปกติ", "เปิดโหมดคืนแบบไม่มีใบเสร็จ", "ยิงหรือเลือกสินค้าที่รับคืนพร้อมจำนวน", "คนขายกด PIN ของตัวเอง แล้วให้ผู้อนุมัติกด PIN", "จ่ายเงินคืนและเก็บหลักฐานไว้ให้บัญชี"], ["Always search for the original sale first — use the normal Return if it exists.", "Open the no-receipt return mode.", "Scan or choose the returned items and quantities.", "The cashier enters their own PIN, then the approver enters theirs.", "Refund the customer and keep the record for accounting."]],
    warnings: [["เพดานราคาคืนคือราคาป้ายวันนี้ เพราะไม่มีบิลต้นทางให้ยึด", "เงินในลิ้นชักไม่พอ = ระบบปฏิเสธ ห้ามหาเงินจากที่อื่นมาจ่ายแทน", "ไม่ออกใบลดหนี้ เพราะไม่มีใบกำกับต้นทางให้อ้าง — เป็นหลักฐานภายใน", "ยอดคืนออกจากลิ้นชักผ่านช่องทางเดียวกับเงินออก จึงตรงกับยอดปิดกะเสมอ", "รายงานนับแยกจากการคืนปกติและเตือนทันทีแม้มีรายการเดียว"], ["The refund is capped at the current shelf price because there is no original bill.", "If the drawer is short the system refuses; never fund the refund from somewhere else.", "No credit note is issued — there is no original tax invoice to reference; this is internal evidence.", "The refund leaves through the same drawer path as cash-out, so shift totals stay correct.", "Reporting counts these separately from normal returns and flags even a single one."]],
    relatedCapabilityIds: ["pos.returns", "pos.operations"],
  }),
  menuGuide({
    id: "pos.use-store-credit", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["บัตรของขวัญและเครดิตร้าน", "Gift cards and store credit"],
    summary: ["เช็คยอดบัตร รับบัตรเป็นวิธีชำระ และแยกจากแต้มสะสมกับวงเงินขายเชื่อ", "Check a card balance, accept it as tender, and keep it distinct from points and receivables."],
    aliases: [["บัตรของขวัญ", "เครดิตร้าน", "gift card", "โค้ดบัตร", "ยอดคงเหลือบัตร"], ["gift card", "store credit", "card balance", "credit code"]],
    anyOfPermissions: ["storecredit.redeem", "storecredit.issue", "storecredit.adjust"],
    prerequisites: [["มีโค้ดบัตรจากลูกค้า", "คนรับบัตรต้องมี storecredit.redeem · การออกบัตรต้องมี storecredit.issue"], ["The customer provides the card code.", "Accepting a card needs storecredit.redeem; issuing one needs storecredit.issue."]],
    steps: [["เช็คยอดบัตรด้วยโค้ดก่อนตกลงกับลูกค้า", "เลือกเครดิตร้านเป็นวิธีชำระในขั้นรับเงิน", "ถ้ายอดบัตรไม่พอ ให้จ่ายส่วนที่เหลือด้วยวิธีอื่นในบิลเดียวกัน", "ยืนยันขายครั้งเดียว"], ["Check the balance by code before agreeing with the customer.", "Choose store credit as tender at payment.", "If the balance is short, cover the rest with another tender on the same bill.", "Confirm the sale once."]],
    warnings: [["การเช็คยอดไม่หักเงิน — ยอดถูกหักในทรานแซกชันเดียวกับการขาย", "เครดิตร้านไม่ใช่เงินสด จึงไม่เข้ายอดที่ควรมีในลิ้นชัก (ร้านรับเงินไปแล้วตอนขายบัตร)", "ยอดบัตรติดลบไม่ได้ ต่างจากแต้มสะสม", "เครดิตร้านไม่ใช่แต้มสะสมและไม่ใช่วงเงินขายเชื่อ"], ["Checking a balance deducts nothing — the deduction happens inside the sale transaction.", "Store credit is not cash and never enters expected drawer cash (the shop was paid when the card was sold).", "A card balance can never go negative, unlike loyalty points.", "Store credit is neither loyalty points nor a receivables credit limit."]],
    relatedCapabilityIds: ["pos.store-credit"],
  }),
  menuGuide({
    id: "pos.pharmacist-authorization", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["จ่ายยาที่ต้องให้เภสัชกรอนุมัติ", "Dispense medicine that needs pharmacist authorization"],
    summary: ["เภสัชกรกด PIN ที่เครื่องขายเพื่อปลดรายการที่ติดกฎ หรือส่งบิลเข้าคิวเมื่อไม่มีเภสัชกรอยู่", "A pharmacist authorizes blocked items with their PIN at the register, or the bill goes to the review queue when none is present."],
    aliases: [["ขายยา", "เภสัชกรอนุมัติ", "ยาต้องมีใบสั่ง", "ส่งเข้าคิวเภสัช", "แนบใบสั่งยา"], ["dispense medicine", "pharmacist approval", "prescription required", "pharmacy queue", "attach prescription"]],
    requiredPermissions: ["pos.sell"],
    prerequisites: [["ร้านตั้งประเภทธุรกิจเป็นร้านขายยาและเปิดการอนุมัติที่เคาน์เตอร์", "ผู้อนุมัติต้องเป็นเภสัชกรที่มีใบอนุญาตในระบบ ไม่ใช่แค่มีสิทธิ์"], ["The shop is configured as a pharmacy with counter authorization enabled.", "The approver must be a licensed pharmacist on record, not merely permission-holding."]],
    steps: [["ยิงสินค้าตามปกติ — ระบบจะบอกว่ารายการไหนติดกฎ", "ถ้าเภสัชกรอยู่หน้าร้าน ให้กด PIN ของเภสัชกรเพื่อปลดรายการนั้น", "ถ้าไม่มีเภสัชกร ให้ส่งบิลเข้าคิวตรวจแล้วรอผล", "ถ้าลูกค้ายื่นใบสั่งยา ให้ถ่ายแนบเป็นหลักฐานก่อนจ่ายยา"], ["Scan items normally — the system names the blocked lines.", "If a pharmacist is present, have them enter their PIN to authorize those lines.", "If not, send the bill to the review queue and wait for the outcome.", "If the customer hands over a prescription, photograph and attach it before dispensing."]],
    warnings: [["เภสัชกรที่ยืนขายเองอนุมัติบิลของตัวเองได้ (ต่างจากส่วนลดมือที่ต้องสองคน)", "เปลี่ยนตะกร้าหลังกด PIN = การอนุมัติหมดอายุ ต้องกดใหม่", "เพดานจำนวนต่อครั้งปลดด้วย PIN ไม่ได้ — ต้องไปแก้ policy ของสินค้า", "ยาที่ต้องมีใบสั่งแพทย์เป็นเรื่องของหน้าร้านเท่านั้น ทางออนไลน์ไม่ปลดให้", "แคชเชียร์แนบหลักฐานได้แต่เปิดดูย้อนหลังไม่ได้ ต้องมีสิทธิ์อ่านหลักฐานทางคลินิก"], ["A pharmacist working the register may authorize their own bill (unlike a manual discount, which needs two people).", "Changing the cart after the PIN expires the authorization; it must be entered again.", "A per-sale quantity cap cannot be unlocked with a PIN — change the product policy instead.", "Prescription-only medicine is a counter-only path; the online channel is never unlocked.", "A cashier can attach evidence but cannot read it back; that needs the clinical-evidence permission."]],
    relatedCapabilityIds: ["pharmacy.workflow", "pharmacy.evidence", "pos.operations"],
  }),
  menuGuide({
    id: "pos.shift-reports", module: "pos", pageId: "pos", route: "/admin/pos-manual",
    title: ["ดู X/Z Report และปิดกะ", "Use X/Z reports and close the shift"], summary: ["ตรวจยอดคาดการณ์ เงินนับจริง variance รายการค้าง และปิดกะของเครื่องเจ้าของกะ", "Review expected cash, counted cash, variance, pending work, and close the owning device shift."],
    aliases: [["X report", "Z report", "รายงานกะ"], ["X report", "Z report", "shift report"]], requiredPermissions: ["pos.shift.report"],
    steps: [["เปิดแท็บกะ", "ดู X report ระหว่างกะ", "เคลียร์ refund allocation/เงินเบิกที่ค้าง", "นับเงินจริง", "ปิดกะและดู Z report"], ["Open Shifts.", "Review the X report mid-shift.", "Clear pending refund allocations and advances.", "Count cash.", "Close and review the Z report."]],
    warnings: [["กะปิดไม่ได้ถ้ามี refund allocation หรือเงินเบิกค้าง", "รายงานตอบเฉพาะ device ที่เป็นเจ้าของกะ"], ["A shift cannot close with pending refund allocations or advances.", "The report is available only to the device that owns the shift."]], relatedCapabilityIds: ["pos.operations", "tax.documents"],
  }),
  {
    id: "pharmacy.case-flow", module: "pharmacy", pageId: "pharmacy", route: "/admin/pharmacy-manual",
    title: both("ติดตามเคสร้านขายยา", "Follow a pharmacy case"),
    summary: both("รับข้อมูล ส่งเข้าคิว และให้เภสัชกรผู้มีใบอนุญาตตัดสินใจ", "Collect intake, queue the case, and let a licensed pharmacist decide."),
    aliases: aliases(["สถานะเคสยา", "คิวเภสัชกร", "ขอข้อมูลเพิ่ม"], ["pharmacy case status", "pharmacist queue", "request more information"]), requiredPermissions: ["pharmacy.assessment.read"],
    prerequisites: lists(["Pharmacy intake เปิดด้วย feature flag", "การตัดสินใจต้องเป็นเภสัชกรมีใบอนุญาต"], ["Pharmacy intake is feature-gated.", "Clinical decisions require a licensed pharmacist."]),
    steps: lists(["เปิดคิว", "เลือกเคสตามสถานะ", "ขอข้อมูลเพิ่มหรือ claim ตามสิทธิ์", "เภสัชกรตรวจและตัดสินใจผ่าน workflow"], ["Open the queue.", "Choose a case by status.", "Request information or claim according to access.", "A pharmacist reviews and decides through the workflow."]),
    warnings: lists(["AI ไม่วินิจฉัยหรืออนุมัติ", "Manager ที่อ่านเคสได้อาจไม่มีสิทธิ์ดูหลักฐาน"], ["AI does not diagnose or approve.", "A Manager who can read a case may still lack evidence access."]), relatedCapabilityIds: ["pharmacy.workflow"],
  },
  {
    id: "system-health.read", module: "system-health", pageId: "system-health", route: "/admin/system-health",
    title: both("อ่านสถานะระบบ", "Read system health"),
    summary: both("ใช้การ์ดสถานะเพื่อแยก provider, job, migration และ request metrics ที่มีข้อมูล", "Use health cards to distinguish provider, job, migration, and available request metrics."),
    aliases: aliases(["ระบบมีปัญหา", "provider ล่ม", "job ไม่ทำงาน"], ["system problem", "provider down", "job not running"]), requiredPermissions: [],
    accessRequirement: "platform_administrator",
    prerequisites: lists(["ต้องผ่าน platform-admin server guard"], ["The platform-admin server guard must pass."]),
    steps: lists(["เปิด System Health", "หา card ที่เตือน", "อ่าน error แบบ fail-soft", "ไปแก้ที่ระบบเจ้าของข้อมูล ไม่ใช่จากหน้านี้"], ["Open System Health.", "Find warning cards.", "Read fail-soft errors.", "Fix the owning subsystem outside this page."]),
    warnings: lists(["หน้านี้ read-only ห้ามเพิ่ม restart หรือ mutation", "ยังไม่ครอบคลุม REST latency และ container CPU/memory"], ["This page is read-only; never add restart or mutation.", "REST latency and container CPU/memory are not covered."]), relatedCapabilityIds: ["system.health"],
  },
  {
    id: "receivables.review", module: "receivables", pageId: "receivables", route: "/admin/receivables",
    title: both("ตรวจลูกหนี้และรับชำระ", "Review and collect receivables"), summary: both("ตรวจวงเงิน หนี้คงค้าง และรับชำระด้วยสิทธิ์ที่เหมาะสม", "Review credit limit, outstanding debt, and collect with the proper access."),
    aliases: aliases(["ดูหนี้ลูกค้า", "รับชำระหนี้", "ขายเชื่อ"], ["customer debt", "collect receivable", "credit sale"]), requiredPermissions: ["ar.view"],
    prerequisites: lists(["รับชำระต้องมี ar.collect"], ["Collection requires ar.collect."]), steps: lists(["ค้นหาลูกหนี้", "ตรวจยอดและเอกสารอ้างอิง", "รับชำระตามช่องทาง", "ตรวจยอดคงเหลือ"], ["Find the account.", "Review balance and source documents.", "Collect through the selected method.", "Verify the remaining balance."]),
    warnings: lists(["ตัดหนี้สูญต้องมี ar.writeoff และเป็นการลดสินทรัพย์"], ["Write-off requires ar.writeoff and reduces an asset."]), relatedCapabilityIds: ["receivables.credit-sales"],
  },
  {
    id: "settings.configure-shop", module: "settings", pageId: "settings", route: "/admin/settings",
    title: both("ตั้งค่าร้านและช่องทาง", "Configure the shop and channels"), summary: both("ตั้งข้อมูลร้าน การรับเงิน ช่องทาง รายงาน และ AI จากหน้า Settings", "Configure store, payments, channels, reports, and AI from Settings."),
    aliases: aliases(["ตั้งค่าร้าน", "เชื่อมช่องทาง", "ตั้ง AI"], ["configure store", "connect channel", "configure AI"]), requiredPermissions: [],
    prerequisites: lists(["มี credential ของบริการที่จะเชื่อม"], ["Have credentials for the service being connected."]), steps: lists(["เปิด Settings", "เลือกหมวด", "กรอกค่าจากผู้ให้บริการ", "บันทึกและตรวจ observed status"], ["Open Settings.", "Choose a section.", "Enter provider-issued values.", "Save and verify observed status."]),
    warnings: lists(["ห้ามใส่ secret ใน NEXT_PUBLIC_*", "active ไม่เท่ากับเชื่อมต่อปกติ"], ["Never put secrets in NEXT_PUBLIC_*.", "active does not mean healthy."]), relatedCapabilityIds: ["settings.channels"],
  },
  {
    id: "billing.read-usage", module: "billing", pageId: "billing", route: "/admin/billing",
    title: both("อ่านโควตาและค่าใช้ AI", "Read AI quota and usage"), summary: both("แยกเครดิตที่คิด ผู้ให้บริการที่เรียก และต้นทุน USD", "Separate billed credits, provider attempts, and attributed USD cost."),
    aliases: aliases(["AI เหลือกี่เครดิต", "ค่า AI", "provider calls"], ["AI credits left", "AI cost", "provider calls"]), requiredPermissions: [],
    prerequisites: lists([], []), steps: lists(["เปิด Billing", "ตรวจ plan และ remaining", "ดู provider calls", "อ่าน unknown/unpriced cost แยกจากศูนย์"], ["Open Billing.", "Review plan and remaining quota.", "Review provider calls.", "Distinguish unknown/unpriced cost from zero."]),
    warnings: lists(["ต้นทุน attributed ไม่ใช่ invoice ผู้ให้บริการ"], ["Attributed cost is not a provider invoice."]), relatedCapabilityIds: ["billing.plan"],
  },
  {
    id: "ai-quality.review", module: "ai-quality", pageId: "ai-quality", route: "/admin/ai-quality",
    title: both("ตรวจเคสคุณภาพ AI", "Review an AI quality case"), summary: both("อ่านข้อเท็จจริงและให้ verdict โดยไม่แก้ข้อมูลลูกค้า", "Review facts and record a verdict without mutating customer data."),
    aliases: aliases(["ตรวจ AI", "AI ตอบผิด", "quality case"], ["review AI", "wrong AI answer", "quality case"]), requiredPermissions: ["ai_quality.view"],
    prerequisites: lists(["การบันทึก verdict ต้องมี ai_quality.review"], ["Recording a verdict requires ai_quality.review."]), steps: lists(["เปิดเคส", "ตรวจ input/output ที่ลดข้อมูลแล้ว", "เลือก verdict และ category", "บันทึก note ที่ไม่ใส่ PII"], ["Open the case.", "Review minimized input/output.", "Choose verdict and category.", "Record a note without PII."]),
    warnings: lists(["อย่าใช้ production PII ใน eval"], ["Do not use production PII in evals."]), relatedCapabilityIds: ["ai.quality"],
  },
  {
    id: "restock.review", module: "restock", pageId: "restock", route: "/admin/restock-subscriptions",
    title: both("ตรวจคิวแจ้งสินค้าเข้า", "Review restock subscriptions"), summary: both("ตรวจความต้องการที่ลูกค้ายินยอมและติดต่อเมื่อของพร้อม", "Review consented demand and contact customers when stock is ready."),
    aliases: aliases(["ลูกค้ารอของ", "สินค้าเข้าแล้วแจ้ง", "restock queue"], ["waiting customers", "notify restock", "restock queue"]), requiredPermissions: ["inbox.view"],
    prerequisites: lists(["ลูกค้า opt in แล้ว", "ช่องทางรองรับการส่งออก"], ["The customer opted in.", "The channel supports outbound messaging."]), steps: lists(["เปิดคิว", "ตรวจสินค้าและสต็อกจริง", "ตรวจตัวตน/ช่องทาง", "พนักงานส่งข้อความที่ตรวจแล้ว"], ["Open the queue.", "Verify live product stock.", "Check identity and channel.", "Staff sends a reviewed message."]),
    warnings: lists(["ไม่ส่งอัตโนมัติจาก AI turn"], ["Do not auto-send from the AI turn."]), relatedCapabilityIds: ["restock.subscriptions"],
  },
  {
    id: "permissions.explain", module: "permissions", pageId: "permissions", route: "/admin/permissions",
    title: both("อ่านและตั้งสิทธิ์ตามบทบาท", "Read and configure role access"), summary: both("แยกสิทธิ์เปิดหน้าออกจาก role rank ที่กำหนดว่าแตะใครได้", "Separate page permission from role rank governing which accounts can be managed."),
    aliases: aliases(["ตั้งสิทธิ์", "role ทำอะไรได้", "ทำไมแก้ user ไม่ได้"], ["configure permissions", "role access", "cannot edit user"]), requiredPermissions: [],
    accessRequirement: "tenant_administrator",
    prerequisites: lists(["ต้องผ่าน server super guard"], ["The server super guard must pass."]), steps: lists(["เปิด Permissions", "เลือกบทบาท", "ตรวจสิทธิ์แต่ละหมวด", "บันทึกแล้วทดสอบด้วยบัญชีบทบาทนั้น"], ["Open Permissions.", "Choose a role.", "Review each permission group.", "Save and test with that role."]),
    warnings: lists(["การมี user.manage ยังแตะ role ที่สูงกว่าหรือเท่ากันไม่ได้", "ซ่อนเมนูไม่ใช่ authorization"], ["user.manage still cannot manage equal/higher roles.", "Menu hiding is not authorization."]), relatedCapabilityIds: ["access.matrix", "users.access"],
  },
  menuGuide({
    id: "inbox.review-mentions", module: "inbox", route: "/admin/inbox/mentions",
    title: ["ตรวจข้อความที่กล่าวถึง", "Review Inbox mentions"], summary: ["รวมข้อความที่กล่าวถึงผู้ใช้เพื่อกลับไปตอบในบทสนทนาต้นทาง", "Review messages that mention the user and return to the source conversation."],
    requiredPermissions: ["inbox.view"], steps: [["เปิด Mentions", "เลือกข้อความ", "เปิดบทสนทนาต้นทางและดำเนินการตามสิทธิ์"], ["Open Mentions.", "Select a mention.", "Open the source conversation and act according to access."]],
    warnings: [["การเห็น mention ไม่ได้ให้สิทธิ์ตอบแทน inbox.reply"], ["Seeing a mention does not grant inbox.reply."]], relatedCapabilityIds: ["inbox.omnichannel"],
  }),
  menuGuide({
    id: "assistant.use-work-assistant", module: "assistant", route: "/admin/assistant",
    title: ["ใช้ AI Work Assistant", "Use AI Work Assistant"], summary: ["ถามความสามารถ วิธีใช้ และข้อมูลร้านผ่านทูลที่ได้รับอนุมัติ", "Ask about capabilities, usage, and shop data through approved tools."],
    steps: [["พิมพ์คำถามให้ระบุคน รายการ หรือช่วงเวลาให้ชัด", "ตรวจแหล่งอ้างอิงและผลจากทูล", "งานสำคัญให้ตรวจ proposal แล้วกดยืนยันเอง"], ["Ask with a clear person, record, or time range.", "Review citations and tool results.", "Review sensitive proposals and confirm them yourself."]],
    warnings: [["Assistant ไม่ query ฐานข้อมูลหรือรัน SQL เอง", "งานกระทบเงิน สต็อก หรือลบข้อมูลเป็น propose-only"], ["The assistant never queries the database or writes SQL directly.", "Money, stock, and deletion remain propose-only."]],
  }),
  menuGuide({
    id: "followup.configure-rules", module: "followup", route: "/admin/followup-rules",
    title: ["ตั้งกฎติดตามลูกค้า", "Configure follow-up rules"], summary: ["กำหนดเงื่อนไขที่สร้างงานติดตามโดยไม่ส่งข้อความทันที", "Define conditions that create follow-up work without immediately sending a message."],
    requiredPermissions: ["followup.view"], prerequisites: [["การแก้กฎต้องมี followup.manage"], ["Editing rules requires followup.manage."]],
    steps: [["เปิด Follow-up Rules", "ตรวจ trigger และเวลาหน่วง", "บันทึกกฎ", "ตรวจงานที่สร้างใน Follow-up Queue"], ["Open Follow-up Rules.", "Review trigger and delay.", "Save the rule.", "Review generated work in Follow-up Queue."]],
    warnings: [["กฎสร้างงาน ไม่ใช่การส่งข้อความอัตโนมัติ"], ["A rule creates work; it does not auto-send a message."]], relatedCapabilityIds: ["followup.retention"],
  }),
  menuGuide({
    id: "locations.manage-branches", module: "locations", route: "/admin/locations",
    title: ["จัดการสาขา", "Manage locations"], summary: ["เพิ่มหรือแก้สาขาที่ใช้กับสต็อก POS และการโอนของ", "Add or edit branches used by inventory, POS, and transfers."],
    requiredPermissions: ["location.manage"], steps: [["เปิด Locations", "เพิ่มหรือแก้ชื่อและข้อมูลสาขา", "ผูกเครื่อง POS หรือใช้สาขากับงานคลัง"], ["Open Locations.", "Add or edit branch details.", "Assign POS devices or use the branch in inventory workflows."]],
    warnings: [["สต็อกและของจองเป็นข้อมูลระดับสาขา"], ["Stock and reservations are branch facts."]], relatedCapabilityIds: ["inventory.branch"],
  }),
  menuGuide({
    id: "pharmacy.try-intake-lab", module: "pharmacy", route: "/admin/pharmacy-intake-lab",
    title: ["ทดลอง Pharmacy Intake", "Try Pharmacy Intake Lab"], summary: ["ทดสอบข้อมูล intake และดูว่าเคสต้องส่งต่อเภสัชกรหรือขอข้อมูลเพิ่ม", "Test intake data and see whether a case escalates or needs more information."],
    requiredPermissions: ["pharmacy.assessment.read"], steps: [["เปิด Intake Lab", "กรอกข้อมูลตัวอย่างที่ไม่ใช่ข้อมูลผู้ป่วยจริง", "ตรวจผลจัดเส้นทางและข้อมูลที่ขาด"], ["Open Intake Lab.", "Enter non-production sample data.", "Review routing and missing information."]],
    warnings: [["ใช้เพื่อทดสอบ flow ไม่ใช่วินิจฉัย", "เภสัชกรมีใบอนุญาตเป็นผู้ตัดสินใจ"], ["This tests the flow; it does not diagnose.", "A licensed pharmacist makes the decision."]], relatedCapabilityIds: ["pharmacy.workflow"],
  }),
  menuGuide({
    id: "pharmacy.process-queue", module: "pharmacy", route: "/admin/pharmacy-queue",
    title: ["ทำงานจากคิวเภสัชกรรม", "Work the pharmacy queue"], summary: ["เปิดเคสตามสถานะ ขอข้อมูลเพิ่ม claim และส่งให้ผู้มีใบอนุญาตตัดสินใจ", "Open cases by status, request information, claim work, and route decisions to licensed staff."],
    requiredPermissions: ["pharmacy.assessment.read"], steps: [["กรองคิวตามความเร่งด่วนและสถานะ", "เปิดเคสและตรวจข้อมูลที่อนุญาตให้เห็น", "ขอข้อมูลเพิ่มหรือ claim ตามสิทธิ์", "ให้เภสัชกร approve หรือ reject"], ["Filter by urgency and status.", "Open the case and review authorized data.", "Request more information or claim it according to access.", "Have a pharmacist approve or reject."]],
    warnings: [["หลักฐานสุขภาพต้องมี pharmacy.evidence.read แยกต่างหาก"], ["Health evidence separately requires pharmacy.evidence.read."]], relatedCapabilityIds: ["pharmacy.workflow"],
  }),
  menuGuide({
    id: "pharmacy.manage-protocols", module: "pharmacy", route: "/admin/pharmacy-protocols",
    title: ["จัดการ Pharmacy Protocols", "Manage pharmacy protocols"], summary: ["ดูแลคำถาม กฎ และเวอร์ชัน protocol ที่ workflow ร้านยาใช้", "Maintain the questions, rules, and versions used by the pharmacy workflow."],
    requiredPermissions: ["pharmacy.protocol.manage"], steps: [["เปิด Protocols", "เลือก protocol และแก้ข้อมูล", "ทบทวนผลกระทบ", "เผยแพร่ตาม workflow ของหน้า"], ["Open Protocols.", "Select and edit a protocol.", "Review the impact.", "Publish through the page workflow."]],
    warnings: [["ห้ามให้โมเดลสร้าง clinical decision แทน protocol และเภสัชกร"], ["Never let the model replace protocols or pharmacist decisions."]], relatedCapabilityIds: ["pharmacy.workflow"],
  }),
  menuGuide({
    id: "pharmacy.manage-licenses", module: "pharmacy", route: "/admin/pharmacy-protocols/licenses",
    title: ["จัดการใบอนุญาตเภสัชกร", "Manage pharmacist licenses"], summary: ["ผูกและตรวจข้อมูลผู้มีใบอนุญาตที่ใช้ตัดสินใจใน pharmacy workflow", "Maintain licensed-pharmacist records used by the pharmacy workflow."],
    accessRequirement: "tenant_administrator", steps: [["เปิด Pharmacist Licenses", "เพิ่มหรือแก้ข้อมูลจากหลักฐานจริง", "ตรวจความถูกต้องก่อนผูกกับ workflow"], ["Open Pharmacist Licenses.", "Add or edit details from real evidence.", "Verify them before using the account in the workflow."]],
    warnings: [["Assistant ห้ามเดาหรือรับรองสถานะใบอนุญาต"], ["The assistant must never infer or certify a license."]], relatedCapabilityIds: ["pharmacy.workflow"],
  }),
  menuGuide({
    id: "pos.configure-devices", module: "pos", route: "/admin/pos-devices",
    title: ["ตั้งเครื่องและ PIN สำหรับ POS", "Configure POS devices and PINs"], summary: ["เพิ่มเครื่อง ผูกสาขา ออก token จับคู่ และดูแล PIN พนักงาน", "Add registers, assign branches, issue pairing tokens, and manage cashier PINs."],
    anyOfPermissions: ["pos.device.manage", "pos.pin.manage"], steps: [["เปิด POS Devices", "เพิ่มหรือเลือกเครื่อง", "ผูกสาขาและตั้ง scanner", "ออก token หรือจัดการ PIN ตามสิทธิ์"], ["Open POS Devices.", "Add or select a register.", "Assign its branch and scanner mode.", "Issue a pairing token or manage PINs according to access."]],
    warnings: [["device token ระบุเครื่อง ไม่ใช่ตัวผู้ขาย", "PIN ต้องตรวจสิทธิ์ server-side ทุก action"], ["A device token identifies a register, not a cashier.", "Every action rechecks the PIN and permission server-side."]], relatedCapabilityIds: ["pos.operations"],
  }),
  menuGuide({
    id: "catalog.configure-packs", module: "product-packs", route: "/admin/product-packs",
    title: ["ตั้งหน่วยขายและบาร์โค้ด Pack", "Configure selling packs"], summary: ["เพิ่มหน่วยขายหลายชิ้นและบาร์โค้ดเสริมโดยอ้างสินค้าแม่", "Add multi-piece selling units and alternate barcodes for a product."],
    requiredPermissions: ["product.view"], steps: [["เปิด Product packs", "เลือกสินค้า", "ระบุรหัส pack ชื่อหน่วย จำนวนชิ้นและราคา", "บันทึกแล้วทดสอบสแกน"], ["Open Product packs.", "Choose a product.", "Set pack code, unit name, piece count, and price.", "Save and test scanning."]],
    warnings: [["จำนวนชิ้นและราคาอ่านจาก backend ห้ามให้ AI กำหนดตอนขาย"], ["Piece count and price come from the backend; AI cannot set them at sale time."]], relatedCapabilityIds: ["catalog.product-packs"],
  }),
  menuGuide({
    id: "catalog.print-labels", module: "product-labels", route: "/admin/product-labels",
    title: ["พิมพ์ฉลากสินค้า", "Print product labels"], summary: ["สร้างสติกเกอร์บาร์โค้ดจากข้อมูลสินค้าและ pack ที่ตั้งไว้", "Print barcode labels from configured product and pack data."],
    requiredPermissions: ["product.view"], steps: [["เปิด Product labels", "ค้นสินค้า/pack", "เลือกจำนวนและรูปแบบ", "ตรวจ preview แล้วพิมพ์"], ["Open Product labels.", "Find a product or pack.", "Choose quantity and layout.", "Review the preview and print."]],
    warnings: [["แก้ barcode ที่ข้อมูลสินค้า ไม่ใช่แก้เฉพาะฉลาก"], ["Fix a barcode in product data, not only on the printed label."]], relatedCapabilityIds: ["catalog.products", "catalog.product-packs"],
  }),
  menuGuide({
    id: "pos.review-readiness", module: "pos", route: "/admin/pos-readiness",
    title: ["ตรวจความพร้อมก่อนเปิด POS", "Review POS readiness"], summary: ["ตรวจ blocker ด้านสินค้า ภาษี refund และนโยบายร้านยาก่อนขายจริง", "Review product, tax, refund, and pharmacy-policy blockers before going live."],
    requiredPermissions: ["pharmacy.policy.read"],
    prerequisites: [["เมนูขึ้นด้วย pharmacy.policy.read แต่ตัวหน้าต้องมี pos.device.manage, product.view และ stock.adjust ครบด้วย"], ["The menu appears with pharmacy.policy.read, but the page itself also needs pos.device.manage, product.view, and stock.adjust."]],
    steps: [["เปิด POS Readiness", "อ่าน blocker แต่ละหมวด", "แก้ในหน้าระบบเจ้าของข้อมูล", "กลับมาตรวจใหม่"], ["Open POS Readiness.", "Review each blocker.", "Fix it in the owning subsystem.", "Run the check again."]],
    warnings: [["ผ่าน readiness ไม่ได้แทนการตรวจ PIN และ permission ตอนขาย"], ["Readiness does not replace PIN and permission checks at sale time."]], relatedCapabilityIds: ["pos.operations", "pharmacy.workflow"],
  }),
  menuGuide({
    id: "commission.review", module: "commission", route: "/admin/commission",
    title: ["ตรวจคอมมิชชัน", "Review commission"], summary: ["ดู rule ตามช่วงเวลา ผลคำนวณ และ clawback จากการคืนสินค้า", "Review effective-dated rules, calculated results, and return clawbacks."],
    requiredPermissions: ["commission.view"], prerequisites: [["การแก้กฎต้องมี commission.manage"], ["Editing rules requires commission.manage."]],
    steps: [["เปิด Commission", "เลือกช่วงเวลา/พนักงาน", "ตรวจยอดและ rule ที่ใช้", "ตรวจรายการคืนที่หักกลับ"], ["Open Commission.", "Choose period or staff.", "Review totals and applied rules.", "Check return clawbacks."]],
    warnings: [["อย่าใช้ rule ปัจจุบันย้อนหลังแทน snapshot ตามช่วงมีผล"], ["Do not apply today's rule retroactively over effective-dated results."]], relatedCapabilityIds: ["commission.staff"],
  }),
  menuGuide({
    id: "inbox.run-realtime-diagnostics", module: "inbox", route: "/admin/inbox/realtime-diagnostics",
    title: ["ทดสอบ Realtime Inbox", "Run Inbox realtime diagnostics"], summary: ["ทดสอบ event และข้อความวินิจฉัยแบบ tenant-scoped โดยไม่ส่งหาลูกค้าจริง", "Test tenant-scoped events and diagnostic messages without contacting real customers."],
    accessRequirement: "tenant_administrator", steps: [["เปิด Realtime Diagnostics", "เลือก Emit เพื่อทดสอบ event หรือ Create Msg เพื่อสร้างข้อมูลวินิจฉัย", "ตรวจผลใน Inbox"], ["Open Realtime Diagnostics.", "Use Emit for an event or Create Msg for diagnostic rows.", "Verify the result in Inbox."]],
    warnings: [["Emit ไม่เขียน row และ Create Msg ไม่รัน AI pipeline/ส่งช่องทางจริง"], ["Emit writes no row; Create Msg does not run AI or send externally."]], relatedCapabilityIds: ["inbox.omnichannel"],
  }),
  menuGuide({
    id: "access.review-audit", module: "audit", route: "/admin/audit",
    title: ["ตรวจ Audit log", "Review the audit log"], summary: ["ค้นว่าใครทำ action สำคัญกับ record ใดและเมื่อไร", "Find who performed an important action on which record and when."],
    accessRequirement: "tenant_administrator", steps: [["เปิด Audit log", "กรอง action/actor/เวลา", "เปิด record ที่เกี่ยวข้องเพื่อยืนยันบริบท"], ["Open Audit log.", "Filter by action, actor, or time.", "Open the related record to confirm context."]],
    warnings: [["Audit เก็บหลักฐานการตัดสินใจ ไม่เก็บ raw AI args หรือข้อมูลสุขภาพ"], ["Audit stores decision evidence, not raw AI arguments or health data."]], relatedCapabilityIds: ["audit.revisions"],
  }),
  menuGuide({
    id: "access.review-revisions", module: "audit", route: "/admin/revisions",
    title: ["ตรวจ Revision History", "Review revision history"], summary: ["ดู snapshot ก่อนแก้และเปรียบเทียบเวอร์ชันของข้อมูลสำคัญ", "Inspect pre-edit snapshots and compare versions of important records."],
    accessRequirement: "tenant_administrator", steps: [["เปิด Revision History", "ค้น SKU หรือ record id", "เลือก revision", "เปรียบเทียบค่าก่อนและหลัง"], ["Open Revision History.", "Search by SKU or record id.", "Choose a revision.", "Compare before and after values."]],
    warnings: [["Revision ไม่ใช่ปุ่ม rollback อัตโนมัติ"], ["Revision history is not an automatic rollback button."]], relatedCapabilityIds: ["audit.revisions"],
  }),
  menuGuide({
    id: "account.update-profile", module: "profile", route: "/admin/profile",
    title: ["ตั้งค่าโปรไฟล์ของฉัน", "Update my profile"], summary: ["แก้รูป ภาษา ธีม และรูปแบบคำสุภาพตามบัญชี", "Update avatar, language, theme, and polite-particle preferences for the account."],
    steps: [["เปิด Profile", "แก้ค่าที่ต้องการ", "บันทึก", "ตรวจว่าภาษาและธีมเปลี่ยนตามบัญชี"], ["Open Profile.", "Change the desired preferences.", "Save.", "Verify language and theme follow the account."]],
    warnings: [["โปรไฟล์ไม่ใช้สำหรับเพิ่มสิทธิ์ให้ตัวเอง"], ["Profile cannot grant permissions to the current account."]],
  }),
  menuGuide({
    id: "onboarding.getting-started", module: "onboarding", route: "/admin/getting-started",
    title: ["เริ่มตั้งค่าร้าน", "Complete Getting Started"], summary: ["ใช้ checklist ตรวจข้อมูลร้าน สินค้า ช่องทาง และ POS ที่ยังขาด", "Use the checklist to find missing shop, product, channel, and POS setup."],
    steps: [["เปิด Getting Started", "เลือกงานที่ยังไม่ครบ", "ทำในหน้าที่ลิงก์ไป", "กลับมาตรวจ checklist"], ["Open Getting Started.", "Choose an incomplete item.", "Complete it on the linked page.", "Return and recheck the list."]],
    warnings: [["การข้าม checklist ไม่ได้ทำให้ dependency พร้อมใช้งาน"], ["Skipping a checklist item does not configure its dependency."]],
  }),
  menuGuide({
    id: "manual.find-instructions", module: "manual", route: "/admin/manual",
    title: ["ค้นคู่มือทั้งระบบ", "Find system instructions"], summary: ["ค้นตามเมนู งาน หรือคำถามที่พบบ่อย แล้วเปิดหน้าทำงานจริง", "Search by menu, task, or FAQ and jump to the real work page."],
    steps: [["เปิด Manual", "ค้นคำหรือเลือกหมวด", "อ่าน prerequisites และข้อควรระวัง", "เปิดลิงก์ไปหน้าจริง"], ["Open Manual.", "Search or choose a section.", "Read prerequisites and warnings.", "Open the real work page."]],
    warnings: [["ข้อมูลร้าน ณ ตอนนี้ต้องตรวจจากหน้าธุรกิจหรือ Assistant tool ไม่ใช่ข้อความคู่มือ"], ["Live shop state must come from the business page or an Assistant tool, not manual prose."]],
  }),
  menuGuide({
    id: "pharmacy.review-mockup", module: "pharmacy", route: "/admin/pharmacy-review-mockup",
    title: ["ดู Pharmacy Review Mockup", "Review the pharmacy design mockup"], summary: ["หน้าจำลองสำหรับทบทวนหน้าตาและ flow review โดยใช้ข้อมูลตัวอย่าง", "A design mockup for reviewing the pharmacist-review UI with sample data."],
    accessRequirement: "tenant_administrator", steps: [["เปิดหน้าจำลอง", "ตรวจ layout และลำดับข้อมูล", "ส่งข้อสังเกตไปแก้ workflow จริงแยกต่างหาก"], ["Open the mockup.", "Review layout and information order.", "Apply feedback separately to the real workflow."]],
    warnings: [["ข้อมูลและปุ่มในหน้านี้เป็น mock ไม่ใช่เคสจริงและไม่ใช่คำตัดสินทางคลินิก"], ["This page is mock data and UI, not a real case or clinical decision."]], relatedCapabilityIds: ["pharmacy.workflow"],
  }),
  menuGuide({
    // `/admin/post` has no index page — only `[id]` and `new`. Linking there is a 404, so the
    // linkable route is the Posts list and the editor subtree is documented, not linked.
    id: "platform.edit-post", module: "posts", route: "/admin/posts",
    coversRoutePrefixes: ["/admin/post"],
    pageId: "post",
    title: ["สร้างและแก้ไข Post", "Create and edit a post"], summary: ["ใช้ฟอร์ม Post สำหรับสร้าง แก้ และเปิดรายละเอียดเนื้อหาระดับแพลตฟอร์ม", "Use the Post form to create, edit, and view platform content."],
    accessRequirement: "platform_administrator", steps: [["เปิด Posts", "เลือก New หรือรายการเดิม", "กรอกและตรวจเนื้อหา", "บันทึกแล้วเปิดหน้ารายละเอียด"], ["Open Posts.", "Choose New or an existing item.", "Edit and review the content.", "Save and open the detail page."]],
    warnings: [["การบันทึกเป็นการเผยแพร่/เปลี่ยนข้อมูลจริงตามสถานะของฟอร์ม ต้องตรวจ audience ก่อน"], ["Saving changes real content according to form status; verify the audience first."]],
  }),
  ...[
    ["platform.architecture", "architecture", "/admin/architecture", "ดูสถาปัตยกรรมระบบ", "Review system architecture", "อ่านโครงสร้าง dependency และขอบเขตระบบระดับแพลตฟอร์ม", "Review platform structure, dependencies, and boundaries."],
    ["platform.tenants", "tenants", "/admin/tenants", "จัดการร้านทั้งหมด", "Manage tenants", "ตรวจร้านและสถานะระดับ fleet โดยไม่ปะปนกับมุมร้านปัจจุบัน", "Review fleet-wide shops without confusing them with current-tenant scope."],
    ["platform.report-schedule", "report-schedule", "/admin/report-schedule", "จัดการตารางส่งรายงาน", "Manage report schedules", "ดูและตั้งงานส่งรายงานตามกำหนดสำหรับทีมส่วนกลาง", "Review and configure scheduled report delivery for central operations."],
    ["platform.roles", "roles", "/admin/roles", "จัดการ Role กลาง", "Manage global roles", "ดูนิยาม role กลางของแพลตฟอร์ม", "Review platform-wide role definitions."],
    ["platform.posts", "posts", "/admin/posts", "จัดการ Posts", "Manage posts", "ดูและจัดการเนื้อหาโพสต์ระดับแพลตฟอร์ม", "Review and manage platform post content."],
    ["platform.files", "files", "/admin/files", "ตรวจไฟล์ในระบบ", "Review stored files", "ตรวจ metadata และ visibility ของไฟล์ตาม guard ที่กำหนด", "Review file metadata and visibility under the configured guards."],
    ["platform.logs", "logs", "/admin/logs", "ตรวจ System logs", "Review system logs", "ค้น log เพื่อวินิจฉัยเหตุการณ์โดยไม่เปิดเผย secret หรือ PII เกินจำเป็น", "Search logs for diagnosis without exposing secrets or unnecessary PII."],
    ["platform.mail-log", "mail-log", "/admin/mail-log", "ตรวจ Mail log", "Review mail logs", "ตรวจประวัติและสถานะการส่งอีเมล", "Review email delivery history and status."],
    ["platform.support", "support-tickets", "/admin/support-tickets", "จัดการ Support tickets", "Manage support tickets", "คัดกรองและติดตามปัญหาที่ผู้ใช้รายงาน", "Triage and track reported user issues."],
    ["platform.operations", "operations-schedule", "/admin/operations-schedule", "ตรวจ Batch และ Cron", "Review batch and cron jobs", "ดูสถานะงาน background และ scheduled jobs", "Review background and scheduled-job state."],
    ["platform.env", "env", "/admin/env", "ตรวจ Environment", "Review environment status", "ตรวจความพร้อมของ config โดยไม่เปิดเผยค่าความลับ", "Review configuration readiness without exposing secret values."],
    ["platform.sql-console", "dev", "/admin/dev/sql-console", "ใช้ Dev SQL Console", "Use the Dev SQL console", "เครื่องมือวินิจฉัยภายในสำหรับผู้ดูแลแพลตฟอร์ม", "Internal diagnostic tooling for platform administrators."],
    ["platform.fake-data", "dev", "/admin/dev/fake", "สร้างข้อมูลทดสอบ", "Create test data", "สร้างข้อมูลสาธิตเฉพาะ environment และ tenant ที่ตั้งใจทดสอบ", "Create demo data only in the intended environment and tenant."],
  ].map(([id, module, route, thTitle, enTitle, thSummary, enSummary]) => menuGuide({
    id, module, route, title: [thTitle, enTitle], summary: [thSummary, enSummary],
    accessRequirement: "platform_administrator",
    steps: [[`เปิด ${thTitle.replace(/^ดู|^ตรวจ|^จัดการ|^ใช้|^สร้าง/, "").trim() || thTitle}`, "ตรวจขอบเขตและข้อมูลก่อนดำเนินการ", "ใช้เฉพาะ action ที่หน้าและ server guard อนุญาต"], [`Open ${enTitle.replace(/^(Review|Manage|Use|Create)\s+/i, "") || enTitle}.`, "Confirm scope and evidence.", "Use only actions allowed by the page and server guard."]],
    warnings: [["เมนูนี้เป็น platform-only และอาจกระทบหลายร้าน"], ["This is platform-only and may affect multiple tenants."]],
  })),
  menuGuide({
    id: "ai.use-playground", module: "ai-quality", route: "/admin/playground",
    title: ["ทดสอบ AI ใน Playground", "Test AI in Playground"], summary: ["ทดสอบ flow แชทและสต็อกในพื้นที่ควบคุม", "Test chat and stock flows in a controlled surface."],
    requiredPermissions: ["ai_quality.view"], steps: [["เปิด Playground", "เลือก scenario ทดสอบ", "ใช้ข้อมูล sandbox", "ตรวจ trace และผลลัพธ์"], ["Open Playground.", "Choose a test scenario.", "Use sandbox data.", "Review trace and output."]],
    warnings: [["ห้ามใส่ production PII หรือใช้แทนการทดสอบ live-model ที่มีขั้นตอนเฉพาะ"], ["Do not enter production PII or treat this as the governed live-model suite."]], relatedCapabilityIds: ["ai.quality"],
  }),
] as const;

/**
 * Starter questions offered at the register.
 *
 * Exported (rather than inlined in the component) so a contract test can prove every chip still
 * resolves to a register guide in both languages — a chip that returns "no verified guide" is
 * worse than no chip, because the cashier reads it as "the system does not do this".
 */
export const POS_REGISTER_SUGGESTIONS: Readonly<Record<"th" | "en", readonly string[]>> = {
  th: ["เมนูขาย", "รับชำระ", "คืนสินค้าและ Void", "คืนของไม่มีใบเสร็จ", "เมนูรับของ", "เมนูมัดจำ", "บัตรของขวัญ", "ขายเชื่อ", "รายงานกะ", "ตั้งค่า scanner"],
  en: ["sale tab", "take payment", "return and void", "no receipt return", "receive PO", "deposit tab", "gift card", "credit sale", "shift report", "scanner settings"],
};
